### ISSUE TITLE
Support multi-layering in FlowNet

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#255]
To support the goal of training a FlowNet model on the Norne Open Dataset, horizontal layering is identified as a potential enabler.

To following steps have been identified:
- [ ]  (Issue: #240) Create function that can either create a 3D or a 2D field of well connections (collapse all connections to 2D) + tests
- [ ] (Issue: #235, PR: #246) Update Mitchels Best Candiate Algorithm to 2D cases + tests 
- [ ] (Issue #242) Create function that allows for 2D Delaunay triangulation + tests
- [ ] (Issue #240) Create function to copy and shift 2D triangulation to desired k-layers from original model + tests (mimicking "seismic")
- [ ] (Issue #243) Create a function that
  - identifies "near vertical" connections based on a max angle --> fault throw (or use existing fault detection?). 
  - Remove connections across faults with a large fault throw.
  - Find "horizontal connections" across faults and assign a fault multiplier.
- [ ] (Issue: #239) Tie-up everything and allow the user to specify which k-layers should be used as FlowNet layers
